// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaSach.Data;

#nullable disable

namespace QuanLyNhaSach.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhaSach.Data.chitietsanpham", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("id_hoadon")
                        .HasColumnType("bigint");

                    b.Property<long>("id_sanpham")
                        .HasColumnType("bigint");

                    b.Property<long>("soluong")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("id_hoadon");

                    b.HasIndex("id_sanpham");

                    b.ToTable("chitietsanphams");
                });

            modelBuilder.Entity("QuanLyNhaSach.Data.hoadon", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("id_taikhoan")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<long>("thanhtien")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("id_taikhoan");

                    b.ToTable("hoadons");
                });

            modelBuilder.Entity("QuanLyNhaSach.Data.sanpham", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("dongia")
                        .HasColumnType("bigint");

                    b.Property<long>("soluong")
                        .HasColumnType("bigint");

                    b.Property<string>("tensanpham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sanphams");
                });

            modelBuilder.Entity("QuanLyNhaSach.Data.taikhoan", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendangnhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("taikhoans");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            hoten = "admin",
                            matkhau = "123",
                            tendangnhap = "admin"
                        });
                });

            modelBuilder.Entity("QuanLyNhaSach.Data.chitietsanpham", b =>
                {
                    b.HasOne("QuanLyNhaSach.Data.hoadon", "hoadon")
                        .WithMany()
                        .HasForeignKey("id_hoadon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNhaSach.Data.sanpham", "sanpham")
                        .WithMany()
                        .HasForeignKey("id_sanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoadon");

                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("QuanLyNhaSach.Data.hoadon", b =>
                {
                    b.HasOne("QuanLyNhaSach.Data.taikhoan", "taikhoan")
                        .WithMany()
                        .HasForeignKey("id_taikhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("taikhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
